name: {{cookiecutter.env_name}}
channels:
  - defaults
dependencies:
  - python==3.8.5
  - numpy
  - pandas
  - pyyaml
  - scikit-learn
  - matplotlib 
  - seaborn
  - conda-forge::hyperopt
  - conda-forge::mlflow
  - conda-forge::python-box
  - conda-forge::python-dotenv
  - conda-forge::shap

  - pip
  - pip:
      - cloudpickle
      - envyaml
      - myautoml
